# Site settings
baseurl = "https://fuquna.ga/"
languageCode = "en-us"
#title = "Hugrid - Grid Theme For Hugo"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-282949-7"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "fuquna.ga"
    #subtitle = "A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
    author = "fuqunaga"
    #description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "unity, unity3d, progiram, c#, shader, hlsl, fuqunaga"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Site"

    # Footer text
    # footertext = '[<i class="fa fa-github" aria-hidden="true"></i>](https://github.com/fuqunaga) [<i class="fa fa-twitter" aria-hidden="true"></i>](https://twitter.com/fuqunaga)'

    social = '[<i class="fa fa-book fa-2x" aria-hidden="true"></i>](https://note.com/fuqunaga) [<i class="fa fa-github fa-2x" aria-hidden="true"></i>](https://github.com/fuqunaga) [<i class="fa fa-twitter fa-2x" aria-hidden="true"></i>](https://twitter.com/fuqunaga) [<i class="fa fa-envelope fa-2x" aria-hidden="true"></i>](mailto:fukhid+contact@gmail.com)'
    # socials = ['[<i class="fa fa-github fa-2x" aria-hidden="true"></i>](https://github.com/fuqunaga)', '[<i class="fa fa-twitter fa-2x" aria-hidden="true"></i>](https://twitter.com/fuqunaga)']

    # add extra-css
    custom_css = ['css/extra.css']
